### PR TITLE
Upgrades 2023-09-04

### LINKED ISSUE #132: Upgrade malariagen_data to >=7.13.0
We need to be able to access Af1.x CNV data, available via malariagen_data v7.13.0, which was recently released.

### PR DESCRIPTION
**Pull request by leehart**
Resolves #132

### CODE REVIEW

**Comment by alimanfoo** [comment]
OSX build failure looks fun to debug... this thread maybe relevant: https://github.com/mamba-org/mamba/issues/1826

**Comment by leehart** [comment]
Using `conda-libmamba-solver` seems to work, re: https://github.com/conda/conda/issues/13041

**Review by alimanfoo — APPROVED** [review]
LGMT, thanks @leehart 🙂

**Review by ahernank — APPROVED** [review]
Looks great, thanks @leehart! 

Very small nit, might be nice to include the version of `conda-libmamba-solver` used.

**Comment by leehart** [comment]
> I don't know if there's a more specific way, akin to `python --version`?

I suppose we could extract the version number from `conda list conda-libmamba-solver`, but I fear this might be flaky / less robust:
```
conda list conda-libmamba-solver | awk '$1 == "conda-libmamba-solver" {print $2}'
```

**Review by ahernank — APPROVED** [review]

**Pull request merged**
