### PR TITLE
Add gsutil package, upgrade pinned environments

### PR DESCRIPTION
**Pull request by leehart**
Ref. #64

### CODE REVIEW

**Comment by alimanfoo** [comment]
Hi @leehart, sorry meant to mention this, normally we don't pin any of the packages listed in the requirements-conda.txt file, but there are a couple of pins there. E.g., numpy is pinned to 1.17.1 and pandas is pinned to 0.25.1, both of which I pinned only because I needed to do that in order to get the environment to solve. Both numpy and pandas have slightly newer releases now, so we should probably upgrade.

What this all means is, please could you:
* Edit the requirements-conda.txt file to pin numpy to 1.17.3 and pandas to 0.25.3.
* Delete the pinned environment files and regenerate them via CI.

Thanks!

**Comment by leehart** [comment]
Cool. Looks like CI has passed.
I'm not authorized to merge, btw.

**Comment by alimanfoo** [comment]
Hi @leehart, I've edited the branch protection settings to add you to the set of users authorised to push to master, which I think means you should be able to merge this PR now. Could you give it a go?

**Comment by leehart** [comment]
OK @alimanfoo @slejdops , this has now been merged.

**Comment by alimanfoo** [comment]
Thanks @leehart, I have tagged this as v2.3.0.

@slejdops please can you upgrade MalariaGEN DataLab on GCP. I think you can do this ASAP, as long as you give users a bit of notice of potential downtime and/or interruptions to service. E.g., I think it would be fine to email out today then do the upgrade tomorrow.

@leehart please could you upgrade the binder submodule in malariagen/vector-ops.

**Comment by slejdops** [comment]
MalariaGEN DataLab on GCP has been upgraded to v2.3.0

**Pull request merged**
