### PR TITLE
Upgrades 2022-06-16

### LINKED ISSUE #115: Add python-gist

### LINKED ISSUE #116: Add rtree
Should be able to add as a conda requirement, it's on conda-forge. Needed for admin unit part of cohorts analysis.

### LINKED ISSUE #117: Upgrade malariagen_data to >=5.0.1
Need to be able to handle missing cohorts and species metadata. Currently in master, should be available from 5.0.1 (to be released shortly).

### PR DESCRIPTION
**Pull request by leehart**
- Resolves  #117 
- Resolves #116 
- Resolves #115
- Removes igv-notebook

### CODE REVIEW

**Comment by leehart** [comment]
@alimanfoo Ready for review.

**Comment by leehart** [comment]
I forgot to re-add the pinned files. I'll do that now.

**Review by alimanfoo — CHANGES_REQUESTED** [review]
Hi @leehart, this LGTM. 

There's just a couple of extra files seem to have crept in, under the .ipynb_checkpoints folder. Would be good to remove those.

**Review by alimanfoo — APPROVED** [review]
Thanks Lee, LGTM.

**Comment by alimanfoo** [comment]
@leehart feel free to merge here, then create a github release with the tag v3.6.0.

**Comment by leehart** [comment]
Thanks @alimanfoo . Will do.

**Pull request merged**
