### PR TITLE
Fix pysamstats 

### LINKED ISSUE #10: pysamstats import error
After creating an environment using binder as a submodule, I'm finding I can't import pysamstats:
```
$ python
Python 3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 02:32:25) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysamstats
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/team112_internal/rp7/src/github/malariagen/Pf-6.0-public-release/deps/conda/envs/Pf-6.0-public-release/lib/python3.6/site-packages/pysamstats/__init__.py", line 8, in <module>
    from .pileup import *
  File "/nfs/team112_internal/rp7/src/github/malariagen/Pf-6.0-public-release/deps/conda/envs/Pf-6.0-public-release/lib/python3.6/site-packages/pysamstats/pileup.py", line 6, in <module>
    import pysamstats.opt as opt
  File "libcfaidx.pxd", line 52, in init pysamstats.opt
AttributeError: module 'pysam.libcfaidx' has no attribute 'FastxRecord'
```
@alimanfoo any suggestions?

### LINKED ISSUE #13: Add imports test to travis CI
Add a test to travis CI that all packages can be imported. Should catch problems like #10.

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR upgrades pysam and pysamstats. Also adds an imports test to verify all Python packages can be imported.

Resolves #10. Resolves #13.

### CODE REVIEW

**Comment by podpearson** [comment]
@alimanfoo , I think you need to change final line of .travis.yml to the following - is that right?
```
  - python binder/imports.py
```
I was going to commit this to fix-pysamstats-alimanfoo-20181219, but worried it might conflict if you're also changing

**Comment by alimanfoo** [comment]
Thanks @podpearson, I'll fix that.

**Comment by alimanfoo** [comment]
OK, CI looks good, going to merge this one.

**Comment by alimanfoo** [comment]
Btw @podpearson if there is an obvious bug like the one you noticed, please feel free to push a change to the PR branch, if you just leave a comment that you've done so then I'll know to pull before I make any further changes.

**Pull request merged**
