### PR TITLE
Big upgrade

### LINKED ISSUE #5: Use pyfaidx instead of pyfasta
@alimanfoo commented on [Sun May 13 2018](https://github.com/malariagen/agam-report-base/issues/12)

Pyfaidx is apparently the new thing. Need version 0.5.4 or later for numpy array support.

### LINKED ISSUE #6: Various package upgrades
bcolz 1.2.1 should be available via conda-forge soon. Not a high priority but would be good to upgrade.

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR upgrades all packages to latest versions, and moves a couple of packages from pip into conda sections. 

Resolves #6, resolves #5.

### CODE REVIEW

**Comment by alimanfoo** [comment]
OK, CI is green, I think this is good to go. @podpearson, @hardingnj, @amakunin, any objections to merging?

**Comment by amakunin** [comment]
no objections from me

**Comment by podpearson** [comment]
LGTM

**Comment by alimanfoo** [comment]
Thanks Nick, I think I'll keep pyfasta around for now for backwards compatibility, but we should aim to migrate new code to using pyfaidx.

**Pull request merged**
