### PR TITLE
Upgrades 2024-06-07

### LINKED ISSUE #138: Upgrade malariagen_data to >=10.0.0

### PR DESCRIPTION
**Pull request by leehart**
Resolves #138

### CODE REVIEW

**Comment by alimanfoo** [comment]
Thanks @leehart. Can we also resolve #137, #136 and #130 while we're doing some upgrades?

**Comment by leehart** [comment]
Ref: issue https://github.com/actions/upload-artifact/issues/478

**Comment by leehart** [comment]
Cannot disable packaging artifact as a `.zip`, e.g. with `compression-level: 0`
Ref: issue https://github.com/actions/upload-artifact/issues/367

**Comment by leehart** [comment]
Hi @alimanfoo . In order to resolve deprecation warnings about GitHub actions `checkout` and `upload-artifact`, I attempted to upgrade them both to `v4`. However, `v4` of `upload-artifact` does not handle multiple uploads (the pinned YAML files) as cleanly as `v2` (or `v3`), as described in issues linked above. It appears that each artifact requires a separate `.zip`, which is a bit awkward. I have demonstrated a way to merge the separate artifacts into a single zip, as a subsequent step here, but the other zips remain, which is also not ideal.

In addition, this has lead to the renaming of the pinned files, at least for convenience, and I'm not sure if other processes are dependent on the pre-existing file names? I expect it should be possible to preserve the original names, somehow.

I'm starting to think the fallout from upgrading the GitHub actions might not have been worth the benefit of resolving a few deprecation warnings, although I suppose they would need addressing eventually. Any thoughts?

**Review by alimanfoo — APPROVED** [review]
Hi @leehart, looks fine to me, the zip file business sounds slightly annoying but it's probably best to keep things up to date, and I don't think the file names matter.

**Pull request merged**
