### PR TITLE
Upgrade msprime to 0.6.2

### LINKED ISSUE #30: Fix msprime import error
The latest travis CI build (see https://github.com/malariagen/binder/pull/29 and https://travis-ci.org/malariagen/binder/jobs/483115513) failed on linux as msprime could not be imported.

### PR DESCRIPTION
**Pull request by alimanfoo**
Hopefully fixes #30.

xref https://github.com/conda-forge/msprime-feedstock/issues/20

### CODE REVIEW

**Comment by hardingnj** [comment]
Trying with build enforced.

**Comment by jeromekelleher** [comment]
Hopefully the most recent build will work. I think what's happening is the that solver **really** wants to minimise the number of 'features' in the environment, so it's preferring older builds with fewer features. These are broken for msprime, so I've asked the admins to move them to the 'broken' label on conda forge: https://github.com/conda-forge/msprime-feedstock/issues/24

Hopefully that's mean that we don't need to force a specific build and these undead zombie builds will finally go away.

**Comment by hardingnj** [comment]
Thanks. I'll keep an eye on that issue.

**Comment by jeromekelleher** [comment]
Can you try again please @hardingnj, with just msprime=0.6.2? The broken packages are out of circulation now, so fingers crossed.

**Comment by alimanfoo** [comment]
Thanks @hardingnj for picking this up :+1:

**Comment by hardingnj** [comment]
Installs `msprime 0.6.2` ok, but unsure why `pdflatex` is failing

**Comment by jeromekelleher** [comment]
Hooray on msprime working! Hopefully it doesn't have anything to do with your pdflatex problems...

**Comment by alimanfoo** [comment]
CI happy now.

**Pull request merged**
